# Stage 1: Build React Frontend
FROM node:18 as react-build
WORKDIR /app

# Copy package.json and package-lock.json (or npm-shrinkwrap.json) from the frontend directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the frontend source code from the frontend directory
COPY ./ ./

# Build the React application
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
