# Stage 2: Set Up Flask Backend
FROM python:3.8

# Set environment variables
ENV FLASK_APP=app.py

ENV FLASK_RUN_HOST=0.0.0.0
# Flask listens on port 80
ENV FLASK_RUN_PORT=30000
# Open the port Flask is running on
EXPOSE 30000

RUN apt-get update -y && \
    apt-get install -y python3-pip

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY ./ /app
CMD ["flask", "run"]